name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3
        with:
          path: content
          fetch-depth: 0

      - name: Checkout Quartz
        uses: actions/checkout@v3
        with:
          repository: jackyzha0/quartz
          path: quartz
          ref: v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Copy config files
        run: |
          cp -r content/.quartz_config/* quartz/

      - name: Install dependencies and build Quartz
        run: |
          cd quartz
          npm i
          cp -r ../content/* content/
          npx quartz build || true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: quartz/public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
